### PR TITLE
Create docker volume for mariadb container

### PR DESCRIPTION
**Pull request by Mixu78**

### CODE REVIEW

**Comment by DrVilepis** [comment]
Dont know shit about docker, will wait for a review from someone who knows docker stuff better.

**Comment by Esinko** [comment]
I'll check this out, hold on...

**Comment by Chicken** [comment]
The docker-compose part is fine but you should probably gitignore the volume folder :D

**Comment by Esinko** [comment]
> The docker-compose part is fine but you should probably gitignore the volume folder :D

Correct.

**Review by Esinko — APPROVED** [review]
LGTM!

**Comment by DrVilepis** [comment]
@Chicken if you give a green flag as well ill be merging this

**Review by Chicken — APPROVED** [review]

**Comment by DrVilepis** [comment]
Merging now

**Pull request merged**
