### PR TITLE
Add self-servicable roles described in #65

### PR DESCRIPTION
**Pull request by lajp**
It would be nice to have some roles also.. The ids should be added to `self_service_roles.txt`

### CODE REVIEW

**Comment by ahnl** [comment]
Can I have a demo of how it works and looks like visually?

**Comment by Chicken** [comment]
https://discord.com/channels/697710787636101202/837031878237880321/949674197632835684

**Comment by kymppi** [comment]
Bad link, doesnt work if you're not arvojäsen.

**Comment by lajp** [comment]
Can't send the demo here because I had desktop notifications on while recording it...

**Comment by kymppi** [comment]
Make new one?

**Comment by Chicken** [comment]
Who tf cares, miksu can access the link and that's all that matters

**Comment by RoyTakanen** [comment]
This is the direct link to discord's cdn: https://cdn.discordapp.com/attachments/837031878237880321/949674196596822116/self-roles.mp4

**Comment by kymppi** [comment]
Okay okay, im just thinking about everyone here. 😠

**Review by ahnl — APPROVED** [review]
> https://discord.com/channels/697710787636101202/837031878237880321/949674197632835684

Awesome, this implementation looks great. 

Thank you, @lajp! 🥇

**Review by DrVilepis — APPROVED** [review]
Looks good to me.

**Pull request merged**
