### PR TITLE
Add a button to voting that does nothing.

### PR DESCRIPTION
**Pull request by lajp**
I am doing this via a pull request in order to get additional opinions on the matter.
Please do leave your comments.

The original commit message:
The intentions behind this commit is to prevent the "real votes" to be
abused for "autistic-reasons". This adds an additionnal button that is
there for individuals that can't stop clicking the buttons
(I admit, they are quite difficult to resist)

This is a feature that was requested by some members of the council.

### CODE REVIEW

**Comment by zikkee** [comment]
veri kuud

**Comment by romeq** [comment]
Looks good 👍🏽

**Comment by lajp** [comment]
An image featuring the button:
image

**Comment by romeq** [comment]
This is very important change as almost whole testausserveri arvojäsen(and jäsen) community loves to press buttons what do, or not do something or anything.
As seen, the welcome sticker react button on #aula was so addictive it was disabled due to it's overuse.
I believe this could be next big step on the community of arvojäsenet.

**Review by ahnl — APPROVED** [review]
This is hilarious yet practical. I approve this. 

Thank you for your contribution!

**Comment by lajp** [comment]
Ok, thanks for the review and comments! Will be merging this shortly.

**Pull request merged**
