### PR TITLE
Fix dockerfile

### PR DESCRIPTION
**Pull request by RoyTakanen**
- Remove unused `CMD`
- Switch to `apt-get`
- Use smaller debian image

### CODE REVIEW

**Comment by luciusmagn** [comment]
alpine image when :kekw:

**Comment by Mixu78** [comment]
> alpine image when :kekw:

I'm working on that actually

**Comment by luciusmagn** [comment]
Very nice, keep us posted @Mixu78

**Comment by DrVilepis** [comment]
Fixed by #49

**Pull request closed without merging**
