### PR TITLE
Build image on the destination server

### PR DESCRIPTION
**Pull request by RoyTakanen**

### CODE REVIEW

**Review by Chicken — APPROVED** [review]
Should be fine. I'm not sure if the resource limits are necessary though?

**Comment by DrVilepis** [comment]
They are kind of, it would soak up the cpu for around 5-10mins for the whole server.

**Comment by Chicken** [comment]
Well, I'm pretty sure the resource limits only apply to a running container. Not the building process.

**Comment by DrVilepis** [comment]
In that case ill request changes soon.

**Comment by lajp** [comment]
Ok, I'll merge this, hope nothing breaks or dies :scream:

**Pull request merged**
