### PR TITLE
Add link to moderation channel to message report interaction response

### PR DESCRIPTION
**Pull request by Mixu78**

### CODE REVIEW

**Review by DrVilepis — CHANGES_REQUESTED** [review]
It would be preferable to only link the channel when the reporter has the moderator role

**Comment by lajp** [comment]
This looks good to me, and seems to work according to my tests. This is a really neat feature and really improves the life of the moderators :) Thanks for this!

Will be merging after the review by @DrVilepis

**Review by DrVilepis — APPROVED** [review]
This should work by all means.

**Comment by lajp** [comment]
Merging now

**Pull request merged**
