### PR TITLE
Bundle blacklist.txt to Docker image

### PR DESCRIPTION
**Pull request by RoyTakanen**
Bundle the regex in blacklist.txt to Docker image.

### CODE REVIEW

**Comment by Esinko** [comment]
We should instead of blacklisting every single file, move relevant files from the project root to their own directory. So we can write
```
!<dir>
```
once and not for each file.

**Comment by Esinko** [comment]
We should also consider using a single folder in the project root for *all* files required for the project to function. Like in Node.js projects, all relevant files are stored in the `src` directory. We should seek a similar solution for this Rust project.

**Comment by lajp** [comment]
These file are already mounted to the container as images, so that they can be modified on runtime if necessary.
See docker-compose.yml for this

**Comment by Esinko** [comment]
> These file are already mounted to the container as images, so that they can be modified on runtime if necessary. See docker-compose.yml for this 

This should be documented and all relevant configuration files should use the same method of inclusion in the container (as in, they will be included via docker-compose.yml or via Dockerfile, but all from the same file).

**Comment by lajp** [comment]
I agree, the files that are included (not excluded) in `.dockerignore` should all be requirements for building the project and nothing more that that. Everything else can and should be mounted as an image for the to be able to be modified quickly if necessary.

**Comment by RoyTakanen** [comment]
After some investigation it appears that the mounts are actually successful in `docker-compose.yml` (removed `!award_id_blacklist.txt` line from `.dockerignore`). This means that the problem is not the mount but something after it. Maybe they files are never read?

**Comment by Esinko** [comment]
> After some investigation it appears that the mounts are actually successful in `docker-compose.yml` (removed `!award_id_blacklist.txt` line from `.dockerignore`). This means that the problem is not the mount but something after it. Maybe the files are never read?

This should be easy enough to figure out with a few breakpoints in the code. I suggest @lajp should build the project in the production server with a few logs about what points are reached and if the file is being read or not.

**Comment by lajp** [comment]
Ok, Ill be closing this pr, and also reverting #23.
I'll start working on some documentation later today.

**Comment by lajp** [comment]
> > After some investigation it appears that the mounts are actually successful in `docker-compose.yml` (removed `!award_id_blacklist.txt` line from `.dockerignore`). This means that the problem is not the mount but something after it. Maybe the files are never read?
> 
> This should be easy enough to figure out with a few breakpoints in the code. I suggest @lajp should build the project in the production server with a few logs about what points are reached and if the file is being read or not.

I think the problem is just that the build is so outdated that it doesn't yet mount the files.

**Comment by Esinko** [comment]
> > > After some investigation it appears that the mounts are actually successful in `docker-compose.yml` (removed `!award_id_blacklist.txt` line from `.dockerignore`). This means that the problem is not the mount but something after it. Maybe the files are never read?
> > 
> > 
> > This should be easy enough to figure out with a few breakpoints in the code. I suggest @lajp should build the project in the production server with a few logs about what points are reached and if the file is being read or not.
> 
> I think the problem is just that the build is so outdated that it doesn't yet mount the files.

I suggest you (@lajp) create a separate issue about the blacklist not working to track fixes.

**Comment by lajp** [comment]
Will do, closing this now

**Pull request closed without merging**
